{"format":1,"version":"4.5.4","settings":"8a8bbe6c32e125d618ab3b18979925e9","files":{"sqlite_rx___init___py":{"hash":"182b2dca469bf063cbcf996d517b03da","index":{"nums":[1,0,0,0,0,0,0],"html_filename":"sqlite_rx___init___py.html","relative_filename":"sqlite_rx/__init__.py"}},"sqlite_rx_auth_py":{"hash":"85b530add9f2a7e59ef6d6878266eb38","index":{"nums":[1,84,0,30,0,0,0],"html_filename":"sqlite_rx_auth_py.html","relative_filename":"sqlite_rx/auth.py"}},"sqlite_rx_client_py":{"hash":"1d3358de13345d2b4367f4b4c054c12d","index":{"nums":[1,69,0,13,0,0,0],"html_filename":"sqlite_rx_client_py.html","relative_filename":"sqlite_rx/client.py"}},"sqlite_rx_exception_py":{"hash":"2b686fb7ab748b6241720c7a2825c517","index":{"nums":[1,10,0,0,0,0,0],"html_filename":"sqlite_rx_exception_py.html","relative_filename":"sqlite_rx/exception.py"}},"sqlite_rx_server_py":{"hash":"50752b6969f41691ea98155c16639c92","index":{"nums":[1,134,0,86,0,0,0],"html_filename":"sqlite_rx_server_py.html","relative_filename":"sqlite_rx/server.py"}},"sqlite_rx_utils_py":{"hash":"e9032c2f4e5bf772e18087fafd46c48f","index":{"nums":[1,10,0,0,0,0,0],"html_filename":"sqlite_rx_utils_py.html","relative_filename":"sqlite_rx/utils.py"}}}}